name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      
    - name: List files
      run: |
        echo "Working directory:"
        pwd
        dir
        echo "Solution file location:"
        if (Test-Path "MIS-Project-.sln") {
            echo "Solution file found"
            Get-Content "MIS-Project-.sln"
        } else {
            echo "Solution file not found"
            exit 1
        }

    - name: Clean solution
      run: |
        echo "Cleaning solution..."
        Remove-Item -Path LoginVendor/NewVendorInfo-DESKTOP-49PLJPG.cs -ErrorAction SilentlyContinue
        Remove-Item -Path LoginVendor/bin -Recurse -ErrorAction SilentlyContinue
        Remove-Item -Path LoginVendor/obj -Recurse -ErrorAction SilentlyContinue

    - name: Restore NuGet packages
      run: |
        echo "Restoring NuGet packages..."
        nuget restore "MIS-Project-.sln" -Verbosity detailed
        echo "NuGet restore completed."

    - name: Build solution
      run: |
        echo "Starting build process..."
        msbuild "MIS-Project-.sln" /p:Configuration=Release /p:Platform="Any CPU" /p:RestorePackagesConfig=true /v:detailed /p:DeployOnBuild=true /p:OutDir="$env:GITHUB_WORKSPACE\bin\Release" /fileLogger /fileLoggerParameters:LogFile=msbuild.log;Verbosity=detailed
        echo "Build process completed."

    - name: Show build logs
      if: always()
      run: |
        echo "MSBuild Log:"
        if (Test-Path "msbuild.log") {
            Get-Content "msbuild.log"
        }

    - name: List build output
      if: always()
      run: |
        echo "Checking workspace contents:"
        Get-ChildItem -Path . -Recurse

    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          *.log
          **/*.binlog
          **/obj/**
          **/bin/**
          MIS-Project-.sln