name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      
    - name: List files
      run: |
        echo "Working directory:"
        pwd
        echo "Current directory contents:"
        dir /s
        echo "Full directory tree:"
        tree /f
      
    - name: Check solution file
      run: |
        echo "Checking for solution file..."
        if (Test-Path "*.sln") {
            Get-ChildItem -Filter *.sln
        } else {
            echo "No solution file found!"
            exit 1
        }

    - name: Restore NuGet packages
      run: |
        echo "Restoring NuGet packages..."
        $solutionFile = Get-ChildItem -Filter *.sln | Select-Object -First 1
        nuget restore $solutionFile.FullName -Verbosity detailed
        echo "NuGet restore completed."

    - name: Build solution
      run: |
        echo "Starting build process..."
        $solutionFile = Get-ChildItem -Filter *.sln | Select-Object -First 1
        msbuild $solutionFile.FullName /p:Configuration=Release /p:Platform="Any CPU" /p:RestorePackagesConfig=true /v:diag /p:DeployOnBuild=true /p:OutDir="$env:GITHUB_WORKSPACE\bin\Release" /bl:msbuild.binlog
        echo "Build process completed."

    - name: Show error log
      if: failure()
      run: |
        echo "Checking for error logs..."
        echo "MSBuild Binary Log:"
        if (Test-Path msbuild.binlog) {
            msbuild -pp:detailed
            msbuild -bl:msbuild.binlog
        }
        echo "Release Logs:"
        Get-ChildItem -Path . -Filter *.log -Recurse | ForEach-Object {
            echo "Log file: $($_.FullName)"
            Get-Content $_.FullName
        }

    - name: List build output
      run: |
        echo "Checking build output directory..."
        Get-ChildItem -Path . -Recurse
      if: always()

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: |
          bin/Release/
          *.log
          msbuild.binlog
      if: always()

    - name: Report build status
      run: |
        echo "Build Status: ${{ job.status }}"
        echo "Runner OS: ${{ runner.os }}"
        echo "Workspace: ${{ github.workspace }}"
      if: always()