name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      
    - name: List files
      run: |
        echo "Working directory:"
        pwd
        echo "Current directory contents:"
        dir /s
        echo "Full directory tree:"
        tree /f
      
    - name: Restore NuGet packages
      run: |
        echo "Restoring NuGet packages..."
        nuget restore "$(pwd)\MIS-Project-.sln" -Verbosity detailed
        echo "NuGet restore completed."

    - name: Build solution
      run: |
        echo "Starting build process..."
        msbuild "$(pwd)\MIS-Project-.sln" /p:Configuration=Release /p:Platform="Any CPU" /p:RestorePackagesConfig=true /v:diag /p:DeployOnBuild=true /p:OutDir="$(pwd)\bin\Release"
        echo "Build process completed."

    - name: Show error log
      if: failure()
      run: |
        echo "Checking for error logs..."
        if (Test-Path LoginVendor\obj\Release\*.log) {
            Get-Content LoginVendor\obj\Release\*.log
        } else {
            echo "No error log files found"
        }
        if (Test-Path msbuild.binlog) {
            Get-Content msbuild.binlog
        } else {
            echo "No MSBuild binary log found"
        }

    - name: List build output
      run: |
        echo "Checking build output directory..."
        if (Test-Path LoginVendor\bin\Release) {
            Get-ChildItem LoginVendor\bin\Release -Recurse
        } else {
            echo "Build output directory not found"
        }
      if: always()

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: LoginVendor\bin\Release\
      if: success()

    - name: Report build status
      run: |
        echo "Build Status: ${{ job.status }}"
        echo "Runner OS: ${{ runner.os }}"
        echo "Workspace: ${{ github.workspace }}"
      if: always()