name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      
    - name: List files
      run: |
        echo "Working directory:"
        pwd
        dir
        echo "Solution file location:"
        if (Test-Path "MIS-Project-.sln") {
            echo "Solution file found"
            Get-Content "MIS-Project-.sln"
        } else {
            echo "Solution file not found"
            exit 1
        }

    - name: Restore NuGet packages
      run: |
        echo "Restoring NuGet packages..."
        nuget restore "MIS-Project-.sln" -Verbosity detailed
        echo "NuGet restore completed."

    - name: Build solution
      run: |
        echo "Starting build process..."
        msbuild "MIS-Project-.sln" `
          /p:Configuration=Release `
          /p:Platform="Any CPU" `
          /p:RestorePackagesConfig=true `
          /v:detailed `
          /p:DeployOnBuild=true `
          /p:OutDir="$env:GITHUB_WORKSPACE\bin\Release" `
          /flp:logfile=msbuild.log;verbosity=detailed `
          /flp1:logfile=msbuild_warn.log;warningsonly `
          /flp2:logfile=msbuild_error.log;errorsonly
        echo "Build process completed."

    - name: Show build logs
      if: always()
      run: |
        echo "MSBuild Log:"
        if (Test-Path "msbuild.log") {
            Get-Content "msbuild.log"
        }
        echo "MSBuild Warnings:"
        if (Test-Path "msbuild_warn.log") {
            Get-Content "msbuild_warn.log"
        }
        echo "MSBuild Errors:"
        if (Test-Path "msbuild_error.log") {
            Get-Content "msbuild_error.log"
        }

    - name: List build output
      if: always()
      run: |
        echo "Checking workspace contents:"
        Get-ChildItem -Path . -Recurse

    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          *.log
          **/*.binlog
          **/obj/**
          **/bin/**
          MIS-Project-.sln