name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      
    - name: Restore NuGet packages
      run: |
        echo "Restoring NuGet packages..."
        nuget restore LoginVendor/LoginVendor.csproj
        echo "NuGet restore completed."

    - name: Build project
      run: |
        echo "Starting build process..."
        msbuild LoginVendor/LoginVendor.csproj /p:Configuration=Release /p:Platform="Any CPU" /p:RestorePackagesConfig=true /v:detailed
        echo "Build process completed."

    - name: List build output
      run: |
        echo "Checking build output directory..."
        dir LoginVendor\bin\Release\
      if: always()

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: LoginVendor\bin\Release\
      if: success()

    - name: Report build status
      run: |
        echo "Build Status: ${{ job.status }}"
        echo "Runner OS: ${{ runner.os }}"
        echo "Workspace: ${{ github.workspace }}"
      if: always()