name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      
    - name: List files
      run: |
        echo "Working directory:"
        pwd
        dir
        echo "Solution file location:"
        if (Test-Path "MIS-Project-.sln") {
            echo "Solution file found"
        } else {
            echo "Solution file not found"
        }

    - name: Restore NuGet packages
      run: |
        echo "Restoring NuGet packages..."
        nuget restore "MIS-Project-.sln" -Verbosity detailed
        echo "NuGet restore completed."

    - name: Build solution
      run: |
        echo "Starting build process..."
        msbuild "MIS-Project-.sln" /p:Configuration=Release /p:Platform="Any CPU" /p:RestorePackagesConfig=true /v:diag /p:DeployOnBuild=true /p:OutDir="$env:GITHUB_WORKSPACE\bin\Release"
        echo "Build process completed."

    - name: Show error log
      if: failure()
      run: |
        echo "Checking for error logs..."
        Get-ChildItem -Path . -Filter *.log -Recurse | ForEach-Object {
            echo "Log file: $($_.FullName)"
            Get-Content $_.FullName
        }
        Get-ChildItem -Path . -Filter *.binlog -Recurse | ForEach-Object {
            echo "Binary log file: $($_.FullName)"
            msbuild -bl:"$($_.FullName)"
        }

    - name: List build output
      if: always()
      run: |
        echo "Checking workspace contents:"
        Get-ChildItem -Path . -Recurse

    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          **/*.log
          **/*.binlog
          **/obj/**
          **/bin/**